use_frameworks!

platform :ios, '8.0'

target 'CMNavigationBar_Example' do
  pod 'CMNavigationBar', :path => '../'

  target 'CMNavigationBar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
